name: Code Coverage

on:
  push:

jobs:
  build:
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint django pylint-django coverage requests
      - name: Ensure proper formatting
        run: >
          pylint --load-plugins pylint_django
          --django-settings-module=spotify_wrapped.settings
          $(git ls-files 'spotify_wrapped/*.py')
      - name: Ensure functionality and code coverage
        run: |
          coverage run --source=./spotify_wrapped manage.py test
          coverage report --fail-under=80
