name: Code Coverage

on: [push]

jobs:
  build:
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django coverage
    - name: Analysing the code with coverage
      run: |
        coverage run manage.py test --source=./spotify_wrapped
        coverage report --fail-under=80
